version: '3'
services:
  web:
    image: simaofsilva/cve-2019-7731
    command: apachectl -D FOREGROUND
    ports:
      - "8000:80"
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mywebsql
    ports:
      - "3306:3306"
