version: '3'
services:
 web:
  image: simaofsilva/cve-2020-7246
  command: apachectl -D FOREGROUND
  ports:
   - "8000:80"
  depends_on:
    - db
 db:
  image: mariadb:10.3.16
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: qdpm
   MYSQL_USER: teste
   MYSQL_PASSWORD: teste
  ports:
   - "3306:3306"
