version: "3"
services:
  os:
    #    image: simaofsilva/cve-2020-9268
    build:
      context: .
    command: apachectl -k start -X -D FOREGROUND
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:80"

  db:
    container_name: soplanning_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: on-failure
    ports:
      - "3306:3306"

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
